version: "3.7"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.local
    container_name: golang-gin.app
    command: ["sh", "wait-for-it.sh", "air", "-d"]
    ports:
      - 8080:8080
    volumes:
      - ./app:/go/src/github.com/44taka/golang-gin
    tty:
      true
    depends_on:
      - postgres
      # - mysql
      # - mysql-test
  postgres:
    image: postgres:latest
    container_name: golang-gin.postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: my_testdb
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432 
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
  # mysql:
  #   image: mysql:latest
  #   container_name: golang-gin.mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: my_testdb
  #     MYSQL_USER: docker
  #     MYSQL_PASSWORD: docker
  #     TZ: 'Asia/Tokyo'
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql/sql:/docker-entrypoint-initdb.d
  #     - ./mysql:/etc/mysql/conf.d
  # mysql-test:
  #   image: mysql:latest
  #   container_name: golang-gin.mysql-test
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: my_testdb
  #     MYSQL_USER: docker
  #     MYSQL_PASSWORD: docker
  #     TZ: 'Asia/Tokyo'
  #   ports:
  #     - "33060:3306"
  #   volumes:
  #     - ./mysql/sql:/docker-entrypoint-initdb.d
  #     - ./mysql:/etc/mysql/conf.d
