version: "3.7"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.local
    container_name: golang-gin.app
    command: ["sh", "wait-for-it.sh", "air", "-d"]
    env_file:
      - ./app/.env
    ports:
      - 8080:8080
    volumes:
      - ./app:/go/src/github.com/44taka/golang-gin
    tty:
      true
    depends_on:
      - postgres
      - postgres-test
  postgres:
    image: postgres:latest
    container_name: golang-gin.postgres
    env_file:
      - ./app/.env
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432 
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
  postgres-test:
    image: postgres:latest
    container_name: golang-gin.postgres-test
    env_file:
      - ./app/.env
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 5433:5432 
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
