version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:202104-01
    steps:
      - checkout
      - run:
          name: Start mysql container
          command: |
            docker-compose up -d mysql
            echo "wating..."
            sleep 15s
      - run:
          name: Start mysql-test container
          command: |
            docker-compose up -d mysql-test
            echo "wating..."
            sleep 15s
      - run:
          name: Build app container
          command: |
            docker-compose build --no-cache app
      - run:
          name: Start app container
          command: |
            docker-compose up -d app
      - run:
          name: Run app test
          command: |
            docker-compose exec app go test ./...

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/check-authentication
      - heroku/push-docker-image

orbs: 
  heroku: circleci/heroku@1.2.6

workflows:
  version: 2
  build-test-deploy:
    jobs:
       - build-and-test:
           filters:
             branches:
               only:
                 - /feature.*/
               ignore:
                 - main
  heroku_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
