version: 2.1

jobs:
  build_and_test:
    machine:
      image: ubuntu-1604:202104-01
    steps:
      - checkout
      - run:
          name: Start mysql container
          command: |
            docker-compose up -d mysql
      - run:
          name: Start mysql-test container
          command: |
            docker-compose up -d mysql-test
      - run:
          name: Build app container
          command: |
            docker-compose build --no-cache app
      - run:
          name: Start app container
          command: |
            docker-compose up -d app
      - run:
          name: Run app test
          command: |
            docker-compose exec app go test ./...
  haroku_deploy:
    docker:
      - image: cimg/base:2021.07
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - heroku/install
      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image:
          process-types: web

orbs: 
  heroku: circleci/heroku@1.2.6

workflows:
  version: 2
  build_and_test:
    jobs:
       - build_and_test:
           filters:
             branches:
               only:
                 - /feature.*/
               ignore:
                 - main
  heroku_deploy:
    jobs:
      - haroku_deploy:
          filters:
            branches:
              only:
                - master
