version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: envファイル作成
          command: |
            echo "test!!"

workflows:
  version: 2
  build-test-deploy:
    jobs:
       - build-and-test:
           filters:
             branches:
               only:
                 - /feature.*/
               ignore:
                 - main
